ROOT=/home/y
include $(ROOT)/share/yahoo_cfg/Make.defs
export BASE_DIR=$(shell pwd)

SUBDIRS = \
	config_util \

include $(ROOT)/share/yahoo_cfg/Make.rules
# Do not place any rules or targets above this line
